export const ChargerData = [
    {
      name: "3 Port QC Quick Wall Charger ",
      price: "  700",
      brand: "Samsung",
      image:
        "https://static-01.daraz.com.np/p/352ffc5855ca4e1a24a84c87e2e671ed.jpg",
      id: "1",
      rating: "4",
      description: "3 Port QC Quick Wall Charger Max Power Output of 20W with 1 Fast 2 Normal Charging",
      stockItem: "45",
      view: "140",
      qty: 1,
    },
    {
      name: "25W PD Super Fast Charger",
      price: " 900",
      brand: "Samsung",
      image:
        "https://static-01.daraz.com.np/p/66b7cdabd7e84c2b84592edf3dcde6df.jpg",
      id: "2",
      rating: "4",
      description: "android phone",
      stockItem: "45",
      view: "140",
      qty: 1,
    },
    {
      name: "OPPO 5V 4A Genuine Fast Travel US Plug Adaptor ",
      price: "  1200",
      brand: "Samsung",
      image:
        "https://static-01.daraz.com.np/p/f88f75c4852c11d8b8308e7fa0b526ef.png",
      id: "3",
      rating: "4",
      description: "OPPO VOOC 5V 4A Genuine Fast Travel US Plug Adaptor With Fast Charging Micro USB Data Sync Cable",
      stockItem: "45",
      view: "140",
      qty: 1,
    },
    {
      name: "ONE PLUS WARP CHARGER GENUINE",
      price: "  1500",
      brand: "Samsung",
      image:
        "https://static-01.daraz.com.np/p/403d122e43ffea46d0c40b4ded827b46.jpg",
      id: "4",
      rating: "4",
      description: "ONE PLUS WARP CHARGER",
      stockItem: "45",
      view: "140",
      qty: 1,
    },
    {
      name: "ONE PLUS WARP CHARGER GENUINE",
      price: "  1700",
      brand: "Samsung",
      image:
        "https://static-01.daraz.com.np/p/403d122e43ffea46d0c40b4ded827b46.jpg",
      id: "1",
      rating: "4",
      description: "android phone",
      stockItem: "45",
      view: "140",
      qty: 1,
    },
    {
      name: "Dash Charging Data Cable",
      price: "  500",
      brand: "Samsung",
      image:
        "https://static-01.daraz.com.np/p/b352c83243069bb8b445f93e572e0297.jpg",
      id: "1",
      rating: "4",
      description: "Give your mobile devices the powerful and safe charging support they deserve. This Wall Charger provides Super Fast Charging with USB-C PD 3.0 PPS at up to max 25W for capable devices. So when you do run low, it's not for long.. Super Fast Charging to stay ready. ",
      stockItem: "45",
      view: "140",
      qty: 1,
    },
    {
      name: "RQ-02 Fast Charging Qualcomm 3.0 Fast Charger",
      price: "  750",
      brand: "Samsung",
      image:
        "https://static-01.daraz.com.np/p/15585b3582025531226b9d09248b5013.jpg",
      id: "1",
      rating: "4",
      description: "android phone",
      stockItem: "45",
      view: "140",
      qty: 1,
    },
    {
      name: "10W/2.1amp Fast Mobile Charger for Huawei",
      price: "  900",
      brand: "Huawei",
      image:
        "https://static-01.daraz.com.np/p/2b4a1271dd8238ad3f340638b37ddf61.jpg",
      id: "1",
      rating: "4",
      description: "android phone",
      stockItem: "45",
      view: "140",
      qty: 1,
    },
    
]