export const mobileData = [
  {
    name: "Samsung Galaxy M04",
    price: " Rs.15999",
    brand: "Samsung",
    image:
      "https://www.samsungplaza.com.np/public/files/C771DD0239E9436-M045.png",
    id: "1",
    rating: "4",
    description: "PLS LCD Infinity-U Display, 720x1600px,OCTA-CORE CPU,5000mAh battery",
    stockItem: "45",
    view: "140",
    qty: 1,
  },
  {
    name: "Samsung Galaxy M14 5G",
    price: " Rs. 22999",
    brand: "samsung",
    image:
      "https://www.samsungplaza.com.np/public/files/DAC96CC92F3BC3F-M14-DarkBlue.png",
    id: "2",
    rating: "5",
    description: "PLS LCD, 1080x2408px,OCTA-CORE CPU,5000mAh battery",
    stockItem: "35",
    view: "145",
    qty: 1,
    
  },
  {
    name: "Samsung Galaxy Fold 4 ",
    price: " Rs. 244999",
    brand: "samsung",
    image:
      "https://www.samsungplaza.com.np/public/files/A0348FEA3A2654E-Fold-4--Beige.png",
    id: "3",
    rating: "4.5",
    description: "PLS LCD, 1080x2408px,OCTA-CORE CPU,5000mAh battery",
    stockItem: "20",
    view: "240",
    qty: 1,
  },
  {
    name: "Samsung Galaxy A70",
    price: " Rs. 40799",
    brand: "samsung",
    image:
      "https://www.samsungplaza.com.np/public/files/22E45B8468DC667-A70-White.png",
    id: "4",
    rating: "3.5",
    description: "PLS LCD, 1080x2408px,OCTA-CORE CPU,5000mAh battery ",
    stockItem: "5",
    view: "300",
    qty: 1,
  },
  {
    name: "Motorola Moto G84 5G 256GB 12GB RAM",
    price: " Rs. 40799",
    brand: "samsung",
    image:
      "https://i.ebayimg.com/images/g/b2IAAOSwYYZlXiXR/s-l960.png",
    id: "5",
    rating: "3.5",
    description: "160.0x74.4x7.6mm, 166g; Glass front, plastic frame, plastic back or eco-leather back; IP54, dust and splash resistant. ",
    stockItem: "5",
    view: "300",
    qty: 1,
  },
  {
    name: "Apple iPhone 13 Pro Max - 1 TB - Gold",
    price: " Rs.191,990",
    brand: "samsung",
    image:
      "https://i.ebayimg.com/images/g/6U0AAOSwkw5iMjJg/s-l1600.jpg",
    id: "6",
    rating: "3.5",
    description: "4K Video Recording, Accelerometer, AMOLED Display, Barometer, Bluetooth Enabled, Camera, Email, Web, Email Access, Facial Recognition, Fast Charging, Flash Light, FM Radio, Front Camera, GPS, Gyro Sensor, HDR Display, LED Flash, Triple Rear Camera, Ultra Wide-Angle Camera, Wide-Angle Camera, Dark Mode, Auto brightness, NFC enabled, Electronic Compass, Gyroscope, Flick-detect Sensor, SAR sensor ",
    stockItem: "5",
    view: "300",
    qty: 1,
  },
  {
    name: "Genuine Xiaomi Redmi Note 11T Pro 5G ",
    price: " Rs. 25000",
    brand: "samsung",
    image:
      "https://i.ebayimg.com/images/g/jn0AAOSwIGBkZ1cQ/s-l960.jpg",
    id: "7",
    rating: "3.5",
    description: "Original Phone, Original Package, Brand NEW!!! 100% Guarantee, Factory Unlocked!!!",
    stockItem: "5",
    view: "300",
    qty: 1,
  },
  {
    name: "Origin Xiaomi Redmi 12R 5G Smartphone 6.79",
    price: " Rs. 35000",
    brand: "samsung",
    image:
      "https://i.ebayimg.com/images/g/D6AAAOSw7gdljmlq/s-l1600.jpg",
    id: "8",
    rating: "3.5",
    description: "3D facial recognition, camera, fast charging, fast wireless charging, front camera, GPS, internet connection, rear camera, speakerphone, vibration, video calls, video camera, voice activated dialing, waterproof, wireless charging",
    stockItem: "5",
    view: "300",
    qty: 1,
  },
   
  ];